sudo: required

language: python
python:
  - "3.6"

addons:
  chrome: stable

services:
  - postgresql

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test

before_script:
  - psql -c 'create database test;' -U postgres

# command to install dependencies
install: 
  - "pip3 install -r requirements.txt"
  - sudo apt-get install -y chromium-chromedriver python3-selenium

# commend to run tests
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - chromedriver --version
  - gunicorn --log-level=indo --bind=127.0.0.1:5000 service:app > gunicorn.log &  # start a Web server in the background
  - sleep 5 # give Web server some time to bind to sockets, etc
  - cat gunicorn.log
  - curl -I http://localhost:5000/  # make sure the service is up
  
script: 
  - nosetests
  - behave

after_sucess:
  - codecov
